# Generated by Django 3.1.3 on 2020-12-19 09:33
from users.models import CustomUser
from django.db import migrations
def add_admin(apps, schema_editor):
    user = CustomUser()
    user.create_user_admin(email="admin@gmail.com",password="Abc123456@")
    
    

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_admin),
    ]
