# Generated by Django 3.1.2 on 2020-10-12 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('urlpage', '0002_auto_20201012_1026'),
        ('users', '0002_url_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Url_User',
            new_name='Domain_User',
        ),
        migrations.AlterField(
            model_name='domain_user',
            name='idurl',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urlpage.domain'),
        ),
    ]
