# Generated by Django 3.1.3 on 2020-11-26 16:10

from django.db import migrations
from users.models import CustomUser
def create_firstuser(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    User = CustomUser()
    User.create_user_admin("admin@gmail.com","Abc123456@")

class Migration(migrations.Migration):

    dependencies = [
          ('users', '0001_initial'),
    ]

    operations = [
         migrations.RunPython(create_firstuser),
    ]