# Generated by Django 3.1.1 on 2020-11-08 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('urlpage', '0010_remove_wordurls_available'),
        ('users', '0003_auto_20201012_1026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal_words',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('iduser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('idword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urlpage.words')),
            ],
        ),
    ]
