# Generated by Django 3.1.1 on 2020-11-10 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=2000, verbose_name='domain')),
                ('isdone', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Urlspage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=2000, verbose_name='url')),
                ('is_valid', models.BooleanField(default=True)),
                ('piclink', models.CharField(default='', max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idDomain', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='urlpage.domain')),
            ],
        ),
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=2000, verbose_name='urls')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WordUrls',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('form_pre', models.CharField(default='', max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idurl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urlpage.urlspage')),
                ('idword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urlpage.words')),
            ],
        ),
    ]
