# Generated by Django 3.1.2 on 2020-10-12 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('urlpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=2000, verbose_name='domain')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='urlspage',
            name='name',
            field=models.CharField(max_length=2000, verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='words',
            name='name',
            field=models.CharField(max_length=2000, verbose_name='urls'),
        ),
        migrations.AddField(
            model_name='urlspage',
            name='idDomain',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='urlpage.domain'),
        ),
    ]
