# Generated by Django 3.1.2 on 2020-10-28 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlpage', '0002_auto_20201012_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordurls',
            name='form_pre',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
