# Generated by Django 3.1.2 on 2020-10-29 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('urlpage', '0003_wordurls_form_pre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordurls',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Words_picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='picture')),
                ('idwords_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urlpage.wordurls')),
            ],
        ),
    ]
