# Generated by Django 3.1.3 on 2020-11-28 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlpage', '0003_auto_20201127_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='words',
            name='suggestion',
            field=models.CharField(default='', max_length=10000, verbose_name='suggest'),
        ),
    ]
