# Generated by Django 3.1.2 on 2020-10-29 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlpage', '0004_auto_20201029_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='words_picture',
            name='picture',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
