# Generated by Django 3.1.2 on 2020-10-30 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlpage', '0005_auto_20201029_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordurls',
            name='checkpic',
            field=models.BooleanField(default=False, max_length=2000),
        ),
    ]
