# Generated by Django 3.1.2 on 2020-10-30 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlpage', '0006_wordurls_checkpic'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordurls',
            name='available',
            field=models.BooleanField(default=True, max_length=2000),
        ),
    ]
