# Generated by Django 3.1.2 on 2020-11-02 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlpage', '0008_auto_20201102_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordurls',
            name='piclink',
        ),
        migrations.AddField(
            model_name='urlspage',
            name='piclink',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
