# Generated by Django 3.1.1 on 2020-11-08 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urlpage', '0009_auto_20201102_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordurls',
            name='available',
        ),
    ]
