# Generated by Django 3.1.1 on 2020-11-09 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlpage', '0010_remove_wordurls_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='isdone',
            field=models.BooleanField(default=True),
        ),
    ]
