# Generated by Django 3.1.2 on 2020-10-30 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('urlpage', '0006_wordurls_checkpic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal_words',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('iduser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('idword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urlpage.words')),
            ],
        ),
        migrations.CreateModel(
            name='Ignore_word_page',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idurl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urlpage.urlspage')),
                ('idword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urlpage.words')),
            ],
        ),
        migrations.CreateModel(
            name='Ignore_word_domain',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idurl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urlpage.domain')),
                ('idword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urlpage.words')),
            ],
        ),
    ]
