# Generated by Django 3.1.2 on 2020-10-30 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words_lib', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ignore_word_page',
        ),
    ]
