# Generated by Django 3.1.3 on 2020-11-27 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='library_words',
            name='meaning',
            field=models.CharField(default='', max_length=10000, verbose_name='meaning'),
        ),
        migrations.AlterField(
            model_name='library_words',
            name='name',
            field=models.CharField(max_length=2000, verbose_name='name'),
        ),
    ]
