# Generated by Django 3.1.3 on 2020-11-27 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20201127_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='library_words',
            name='meaning',
        ),
    ]
